/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementDisp: typeof import('./src/components/AnnouncementDisp.vue')['default']
    AppointmentDisp: typeof import('./src/components/AppointmentDisp.vue')['default']
    EULA: typeof import('./src/components/editRecord/EULA.vue')['default']
    LocationItem: typeof import('./src/components/editRecord/LocationItem.vue')['default']
    LocationSelect: typeof import('./src/components/editRecord/LocationSelect.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NElement: typeof import('naive-ui')['NElement']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NP: typeof import('naive-ui')['NP']
    NQrCode: typeof import('naive-ui')['NQrCode']
    NResult: typeof import('naive-ui')['NResult']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    PersonalInfo: typeof import('./src/components/PersonalInfo.vue')['default']
    ProblemDescribe: typeof import('./src/components/editRecord/ProblemDescribe.vue')['default']
    RecordDetail: typeof import('./src/components/RecordDetail.vue')['default']
    RecordDisp: typeof import('./src/components/editRecord/RecordDisp.vue')['default']
    RecordItem: typeof import('./src/components/RecordItem.vue')['default']
    RepairComment: typeof import('./src/components/editRecord/RepairComment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
